
package com.architect.webservice.service.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "cxfJaxUserService", targetNamespace = "http://cxf.service.webservice.architect.com/", wsdlLocation = "http://127.0.0.1:10000/cxf/jax/user?wsdl")
public class CxfJaxUserService
    extends Service
{

    private final static URL CXFJAXUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFJAXUSERSERVICE_EXCEPTION;
    private final static QName CXFJAXUSERSERVICE_QNAME = new QName("http://cxf.service.webservice.architect.com/", "cxfJaxUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:10000/cxf/jax/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFJAXUSERSERVICE_WSDL_LOCATION = url;
        CXFJAXUSERSERVICE_EXCEPTION = e;
    }

    public CxfJaxUserService() {
        super(__getWsdlLocation(), CXFJAXUSERSERVICE_QNAME);
    }

    public CxfJaxUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFJAXUSERSERVICE_QNAME, features);
    }

    public CxfJaxUserService(URL wsdlLocation) {
        super(wsdlLocation, CXFJAXUSERSERVICE_QNAME);
    }

    public CxfJaxUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFJAXUSERSERVICE_QNAME, features);
    }

    public CxfJaxUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfJaxUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CxfJaxUserInterface
     */
    @WebEndpoint(name = "cxfJaxUserInterfacePort")
    public CxfJaxUserInterface getCxfJaxUserInterfacePort() {
        return super.getPort(new QName("http://cxf.service.webservice.architect.com/", "cxfJaxUserInterfacePort"), CxfJaxUserInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfJaxUserInterface
     */
    @WebEndpoint(name = "cxfJaxUserInterfacePort")
    public CxfJaxUserInterface getCxfJaxUserInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.service.webservice.architect.com/", "cxfJaxUserInterfacePort"), CxfJaxUserInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFJAXUSERSERVICE_EXCEPTION!= null) {
            throw CXFJAXUSERSERVICE_EXCEPTION;
        }
        return CXFJAXUSERSERVICE_WSDL_LOCATION;
    }

}
