
package com.architect.webservice.service.jax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "jaxUserService", targetNamespace = "http://jax.service.webservice.architect.com/", wsdlLocation = "http://127.0.0.1:10000/jax/user?wsdl")
public class JaxUserService
    extends Service
{

    private final static URL JAXUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAXUSERSERVICE_EXCEPTION;
    private final static QName JAXUSERSERVICE_QNAME = new QName("http://jax.service.webservice.architect.com/", "jaxUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:10000/jax/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAXUSERSERVICE_WSDL_LOCATION = url;
        JAXUSERSERVICE_EXCEPTION = e;
    }

    public JaxUserService() {
        super(__getWsdlLocation(), JAXUSERSERVICE_QNAME);
    }

    public JaxUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXUSERSERVICE_QNAME, features);
    }

    public JaxUserService(URL wsdlLocation) {
        super(wsdlLocation, JAXUSERSERVICE_QNAME);
    }

    public JaxUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXUSERSERVICE_QNAME, features);
    }

    public JaxUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JaxUserInterface
     */
    @WebEndpoint(name = "jaxUserInterfacePort")
    public JaxUserInterface getJaxUserInterfacePort() {
        return super.getPort(new QName("http://jax.service.webservice.architect.com/", "jaxUserInterfacePort"), JaxUserInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JaxUserInterface
     */
    @WebEndpoint(name = "jaxUserInterfacePort")
    public JaxUserInterface getJaxUserInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jax.service.webservice.architect.com/", "jaxUserInterfacePort"), JaxUserInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXUSERSERVICE_EXCEPTION!= null) {
            throw JAXUSERSERVICE_EXCEPTION;
        }
        return JAXUSERSERVICE_WSDL_LOCATION;
    }

}
